### ISSUE TITLE
回调函数不执行

### ISSUE THREAD

**Issue by MaSiYuan** [hss01248/PhotoOut#4]
PhotoUtil.init(this);
                PhotoUtil.begin()
//                        .setFromCamera(true)
                        .setNeedCropWhenOne(true)
                        .setNeedCompress(true)
                        .setMaxSelectCount(1)
                        .setCropMuskOval()
                        .setSelectGif()
                        .start(this, new PhotoCallback() {
                            @Override
                            public void onFail(String msg, Throwable r) {
                                super.onFail(msg, r);
                            }

                            @Override
                            public void onSuccessSingle(String originalPath, String compressedPath) {
                                super.onSuccessSingle(originalPath, compressedPath);
                            }

                            @Override
                            public void onSuccessMulti(List<String> originalPaths, List<String> compressedPaths) {
                                super.onSuccessMulti(originalPaths, compressedPaths);
                            }

                            @Override
                            public void onCancel() {
                                super.onCancel();
                            }
                        });选完照片没有执行回掉函数

**Comment by hss01248** [comment]
@MaSiYuan 已更新
