### ISSUE TITLE
Gradle失败

### ISSUE THREAD

**Issue by guanyunbai** [hss01248/PhotoOut#7]
Error:Failed to resolve: annotationProcessor
Error:Failed to resolve: com.github.hss01248.PhotoOut:1.0.2:

**Comment by guanyunbai** [comment]
PhotoPicker:fresco:1.0.7已成功添加

**Comment by hss01248** [comment]
compile'com.github.hss01248:PhotoOut:1.0.2'  分包后我标点没改过来
